/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
// DemoMita.jsx
import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Mita(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/mita!.glb')
  const { actions } = useAnimations(animations, group)

  // Play the "Idle" animation once it's loaded
  useEffect(() => {
    if (actions?.Idle) {
      actions.Idle.play()
    }
  }, [actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={76.131}>
          <group name="MitaSideGirlfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Body" rotation={[-Math.PI / 2, 0, 0]} />
                <group
                  name="Camera001"
                  position={[735.889, 495.831, 692.579]}
                  rotation={[-Math.PI, 0.756, 2.68]}
                  scale={100}
                >
                  <group name="Object_8" />
                </group>
                <group
                  name="Camera002"
                  position={[735.889, 495.831, 692.579]}
                  rotation={[-Math.PI, 0.756, 2.68]}
                  scale={100}
                >
                  <group name="Object_13" />
                </group>
                <group name="Hair" rotation={[-Math.PI / 2, 0, 0]} />
                <group name="Head" rotation={[-Math.PI / 2, 0, 0]} />
                <group
                  name="Light001"
                  position={[407.625, 590.386, -100.545]}
                  rotation={[1.89, 0.881, -2.045]}
                  scale={100}
                >
                  <group name="Object_5" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_6" />
                  </group>
                </group>
                <group
                  name="Light002"
                  position={[407.625, 590.386, -100.545]}
                  rotation={[1.89, 0.881, -2.045]}
                  scale={100}
                >
                  <group name="Object_10" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_11" />
                  </group>
                </group>
                <group name="MitaUsual_(merge)">
                  <group name="MitaUsual">
                    <group name="Object_23">
                      <skinnedMesh
                        name="0"
                        geometry={nodes['0'].geometry}
                        material={materials['Face.004']}
                        skeleton={nodes['0'].skeleton}
                        morphTargetDictionary={nodes['0'].morphTargetDictionary}
                        morphTargetInfluences={nodes['0'].morphTargetInfluences}
                      />
                      <group name="Object_25" rotation={[-Math.PI / 2, 0, 0]} />
                      <group name="Object_26" />
                      <group name="Object_27" rotation={[-Math.PI / 2, 0, 0]} />
                      <skinnedMesh
                        name="Object_28"
                        geometry={nodes.Object_28.geometry}
                        material={materials['Cloth.004']}
                        skeleton={nodes.Object_28.skeleton}
                      />
                      <group name="Object_29" rotation={[-Math.PI / 2, 0, 0]} />
                      <skinnedMesh
                        name="Object_30"
                        geometry={nodes.Object_30.geometry}
                        material={materials['Hairs.004']}
                        skeleton={nodes.Object_30.skeleton}
                      />
                      <skinnedMesh
                        name="Object_31"
                        geometry={nodes.Object_31.geometry}
                        material={materials['Cloth.004']}
                        skeleton={nodes.Object_31.skeleton}
                      />
                      <group name="Object_32" rotation={[-Math.PI / 2, 0, 0]} />
                      <skinnedMesh
                        name="Object_33"
                        geometry={nodes.Object_33.geometry}
                        material={materials['Cloth.001']}
                        skeleton={nodes.Object_33.skeleton}
                      />
                      <group name="Object_34" rotation={[-Math.PI / 2, 0, 0]} />
                      <skinnedMesh
                        name="Object_35"
                        geometry={nodes.Object_35.geometry}
                        material={materials['Body.004']}
                        skeleton={nodes.Object_35.skeleton}
                      />
                      <group name="Object_36" rotation={[-Math.PI / 2, 0, 0]} />
                      <skinnedMesh
                        name="Object_37"
                        geometry={nodes.Object_37.geometry}
                        material={materials['Cloth.004']}
                        skeleton={nodes.Object_37.skeleton}
                      />
                      <group name="Object_38" rotation={[-Math.PI / 2, 0, 0]} />
                      <skinnedMesh
                        name="Object_39"
                        geometry={nodes.Object_39.geometry}
                        material={materials['Cloth.001']}
                        skeleton={nodes.Object_39.skeleton}
                      />
                      <primitive object={nodes._rootJoint} />
                    </group>
                  </group>
                </group>
                <group name="Pantyhose" rotation={[-Math.PI / 2, 0, 0]} />
                <group name="Shoes" rotation={[-Math.PI / 2, 0, 0]} />
                <group name="Skirt" rotation={[-Math.PI / 2, 0, 0]} />
                <group name="Sweater001" rotation={[-Math.PI / 2, 0, 0]} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/mita!.glb')
