/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: vanessacampbell701 (https://sketchfab.com/vanessacampbell701)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mc-from-miside-ec46be35652a4d8aa614cb2ef9df0353
Title: MC from MiSide
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ position = [0, 0, 0], scale = 1, animationName = 'Player Idle', ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/mc_from_miside.glb')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    // Whenever animationName changes, stop the previous action and play the new one
    if (!actions || !animationName) return

    // If the animation exists, play it
    const action = actions[animationName]
    if (action) {
      action.reset().fadeIn(0.3).play()
    }

    // On unmount or when animation changes, fade it out
    return () => {
      if (action) {
        action.fadeOut(0.3)
      }
    }
  }, [animationName, actions])

  return (
    <group ref={group} {...props} dispose={null} position={position} scale={scale}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={176.474}>
          <group name="Player_fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Player_">
                  <group name="Player">
                    <group name="Object_6">
                      <primitive object={nodes._rootJoint} />
                      <skinnedMesh
                        name="Object_9"
                        geometry={nodes.Object_9.geometry}
                        material={materials.PlayerArms}
                        skeleton={nodes.Object_9.skeleton}
                      />
                      <skinnedMesh
                        name="Object_11"
                        geometry={nodes.Object_11.geometry}
                        material={materials.PlayerClothes}
                        skeleton={nodes.Object_11.skeleton}
                      />
                      <skinnedMesh
                        name="Object_13"
                        geometry={nodes.Object_13.geometry}
                        material={materials.PlayerHair}
                        skeleton={nodes.Object_13.skeleton}
                      />
                      <skinnedMesh
                        name="Object_15"
                        geometry={nodes.Object_15.geometry}
                        material={materials.PlayerFace}
                        skeleton={nodes.Object_15.skeleton}
                      />
                      <group name="Object_8" rotation={[-Math.PI / 2, 0, 0]} />
                      <group name="Object_10" rotation={[-Math.PI / 2, 0, 0]} />
                      <group name="Object_12" rotation={[-Math.PI / 2, 0, 0]} />
                      <group name="Object_14" rotation={[-Math.PI / 2, 0, 0]} />
                      <group name="Arms" rotation={[-Math.PI / 2, 0, 0]} />
                      <group name="Clothes" rotation={[-Math.PI / 2, 0, 0]} />
                      <group name="Hair" rotation={[-Math.PI / 2, 0, 0]} />
                      <group name="Head" rotation={[-Math.PI / 2, 0, 0]} />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/mc_from_miside.glb')
