/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import DemoComputer from '../components/DemoComputer.jsx'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/room.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_437.geometry}
        material={materials.mat_58}
        position={[0.552, 0.653, -0.396]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_438.geometry}
        material={materials.mat_59}
        position={[0.67, 0.703, -1.049]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_440.geometry}
        material={materials.mat_61}
        position={[0.716, 0.664, -1.044]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_441.geometry}
        material={materials.mat_61}
        position={[3.785, 0.916, 0.273]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_442.geometry}
        material={materials.mat_61}
        position={[3.806, 1.154, -1.359]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_443.geometry}
        material={materials.mat_62}
        position={[3.958, 1.254, 0.256]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_444.geometry}
        material={materials.mat_63}
        position={[0.725, 0.715, -0.792]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_445.geometry}
        material={materials.mat_64}
        position={[0.812, 0.863, 1.427]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_446.geometry}
        material={materials.mat_64}
        position={[1.312, 0.417, 0.803]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_447.geometry}
        material={materials.mat_64}
        position={[1.131, 0.109, 0.694]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      {/* <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_448.geometry}
        material={materials.mat_65}
        position={[0.662, 0.943, -1.777]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      /> */}
      {/* <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_449.geometry}
        material={materials.mat_65}
        position={[0.759, 0.305, -1.723]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      /> */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_450.geometry}
        material={materials.mat_65}
        position={[1.035, 0.35, -1.792]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_452.geometry}
        material={materials.mat_67}
        position={[0.854, 0.661, -1.322]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_454.geometry}
        material={materials.mat_69}
        position={[3.857, 0.771, -1.222]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_455.geometry}
        material={materials.mat_70}
        position={[0.926, 1.464, -2.177]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_456.geometry}
        material={materials.mat_70}
        position={[3.284, 1.444, -2.118]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_459.geometry}
        material={materials.mat_71}
        position={[0.515, 0.712, -0.571]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_460.geometry}
        material={materials.mat_71}
        position={[0.587, 0.743, -0.739]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_461.geometry}
        material={materials.mat_71}
        position={[3.73, 0.764, -1.22]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_462.geometry}
        material={materials.mat_72}
        position={[1.239, 0.078, -0.155]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_463.geometry}
        material={materials.mat_72}
        position={[3.79, 1.127, -1.543]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_464.geometry}
        material={materials.mat_73}
        position={[2.811, 0.548, -1.815]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_465.geometry}
        material={materials.mat_74}
        position={[3.28, 0.036, 1.954]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_466.geometry}
        material={materials.mat_74}
        position={[3.426, 0.084, 2.053]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_467.geometry}
        material={materials.mat_74}
        position={[3.338, 0.03, 1.794]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_468.geometry}
        material={materials.mat_74}
        position={[3.431, 0.082, 1.82]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_469.geometry}
        material={materials.mat_74}
        position={[3.541, 0.033, 1.733]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_470.geometry}
        material={materials.mat_74}
        position={[3.75, 0.046, 1.64]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_471.geometry}
        material={materials.mat_74}
        position={[0.772, 0.035, -0.431]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_473.geometry}
        material={materials.mat_74}
        position={[0.779, 0.034, -0.533]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_474.geometry}
        material={materials.mat_74}
        position={[1.172, 0.118, -0.567]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_475.geometry}
        material={materials.mat_74}
        position={[0.558, 0.742, -1.274]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_476.geometry}
        material={materials.mat_74}
        position={[1.973, 0.791, -2.28]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_477.geometry}
        material={materials.mat_75}
        position={[2.17, 0.905, 2.097]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_478.geometry}
        material={materials.mat_76}
        position={[3.291, 1.222, -2.088]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_479.geometry}
        material={materials.mat_77}
        position={[3.285, 0.332, -2.01]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_480.geometry}
        material={materials.mat_78}
        position={[3.794, 0.805, -1.431]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_481.geometry}
        material={materials.mat_79}
        position={[3.776, 0.035, 0.562]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_482.geometry}
        material={materials.mat_137}
        position={[2.429, 0.932, -2.248]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_483.geometry}
        material={materials.mat_81}
        position={[0.387, 1.206, -0.809]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_485.geometry}
        material={materials.mat_82}
        position={[1.201, 0.3, 1.372]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_488.geometry}
        material={materials.mat_85}
        position={[3.728, 0.352, 1.883]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_489.geometry}
        material={materials.mat_86}
        position={[2.177, 0.406, -2.211]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_490.geometry}
        material={materials.mat_87}
        position={[0.711, 0.587, 1.687]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_491.geometry}
        material={materials.mat_88}
        position={[3.824, 1.051, 0.064]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_492.geometry}
        material={materials.mat_89}
        position={[2.117, 1.072, -0.006]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_495.geometry}
        material={materials.mat_91}
        position={[1.227, 1.584, 2.105]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_499.geometry}
        material={materials.mat_92}
        position={[3.211, 1.017, -2.011]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_370.geometry}
        material={materials.mat_99}
        position={[3.728, 0.492, 0.249]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_371.geometry}
        material={materials.mat_99}
        position={[3.722, 0.959, -0.432]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_372.geometry}
        material={materials.mat_100}
        position={[0.079, 1.314, 0.301]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_373.geometry}
        material={materials.mat_100}
        position={[2.199, 1.354, -2.416]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_376.geometry}
        material={materials.mat_103}
        position={[1.685, 0.559, -1.75]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_378.geometry}
        material={materials.mat_104}
        position={[1.044, 0.723, -0.946]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_379.geometry}
        material={materials.mat_198}
        position={[1.044, 0.714, -0.945]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_380.geometry}
        material={materials.mat_105}
        position={[0.24, 1.305, 0.344]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_381.geometry}
        material={materials.mat_105}
        position={[2.177, 1.314, -2.332]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_400.geometry}
        material={materials.mat_184}
        position={[1.078, 0.082, 0.652]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_405.geometry}
        material={materials.mat_112}
        position={[0.742, 0.68, -0.39]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_408.geometry}
        material={materials.mat_114}
        position={[0.4, 0.233, -1.278]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_409.geometry}
        material={materials.mat_115}
        position={[3.435, 0.183, 0.057]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_410.geometry}
        material={materials.mat_116}
        position={[0.909, 0.383, 0.402]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_412.geometry}
        material={materials.mat_195}
        position={[1.183, 0.072, 0.083]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_417.geometry}
        material={materials.mat_120}
        position={[1.343, 0.266, 1.813]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_418.geometry}
        material={materials.mat_121}
        position={[2.199, 0.518, 2.044]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_421.geometry}
        material={materials.mat_124}
        position={[0.389, 1.23, -0.778]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_425.geometry}
        material={materials.mat_178}
        position={[3.514, 0.376, -2.052]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_426.geometry}
        material={materials.mat_126}
        position={[4.012, 0.968, 1.089]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_427.geometry}
        material={materials.mat_126}
        position={[4.046, 0.757, 1.462]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_428.geometry}
        material={materials.mat_126}
        position={[4.024, 0.764, 0.767]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_430.geometry}
        material={materials.mat_128}
        position={[2.141, 0.008, 1.886]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_431.geometry}
        material={materials.mat_128}
        position={[2.359, 0.008, 0.11]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_432.geometry}
        material={materials.mat_128}
        position={[3.768, 0.008, 1.085]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_433.geometry}
        material={materials.mat_128}
        position={[0.921, 0.009, -1.398]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_434.geometry}
        material={materials.mat_129}
        position={[3.791, 0.415, -1.314]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_351.geometry}
        material={materials.mat_76}
        position={[0.479, 1.291, -1.61]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_356.geometry}
        material={materials.mat_137}
        position={[3.219, 1.601, 2.015]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_357.geometry}
        material={materials.mat_137}
        position={[3.645, 1.874, -0.564]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_360.geometry}
        material={materials.mat_138}
        position={[0.391, 1.007, -1.042]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_361.geometry}
        material={materials.mat_138}
        position={[0.514, 0.682, -0.902]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_363.geometry}
        material={materials.mat_140}
        position={[0.597, 0.944, -0.754]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_364.geometry}
        material={materials.mat_141}
        position={[3.751, 0.78, -1.477]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_322.geometry}
        material={materials.mat_146}
        position={[1.035, 0.35, -1.792]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_323.geometry}
        material={materials.mat_147}
        position={[0.809, 0.52, -1.201]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_325.geometry}
        material={materials.mat_149}
        position={[1.581, 0.414, -1.719]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_327.geometry}
        material={materials.mat_70}
        position={[0.418, 1.46, -1.639]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_330.geometry}
        material={materials.mat_71}
        position={[0.859, 0.653, -0.392]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_331.geometry}
        material={materials.mat_71}
        position={[1.104, 0.654, -0.393]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_345.geometry}
        material={materials.mat_155}
        position={[0.966, 0.039, -0.486]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_302.geometry}
        material={materials.mat_156}
        position={[2.096, 2.006, -0.146]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_304.geometry}
        material={materials.mat_158}
        position={[0.973, 0.655, -0.407]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_305.geometry}
        material={materials.mat_159}
        position={[0.505, 1.471, -1.364]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_306.geometry}
        material={materials.mat_160}
        position={[3.693, 0.911, 0.075]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_308.geometry}
        material={materials.mat_162}
        position={[3.31, 1.509, 2.055]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_310.geometry}
        material={materials.mat_164}
        position={[3.234, 1.011, 2.057]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_311.geometry}
        material={materials.mat_165}
        position={[3.797, 1.176, -1.261]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_313.geometry}
        material={materials.mat_166}
        position={[3.785, 0.916, 0.273]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_315.geometry}
        material={materials.mat_167}
        position={[3.958, 1.254, 0.256]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_276.geometry}
        material={materials.mat_170}
        position={[2.171, 2.24, -0.03]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_279.geometry}
        material={materials.mat_173}
        position={[1.257, 0.686, -0.39]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_280.geometry}
        material={materials.mat_174}
        position={[0.498, 1.965, -1.476]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_281.geometry}
        material={materials.mat_175}
        position={[3.172, 0.381, -2.048]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_283.geometry}
        material={materials.mat_176}
        position={[0.387, 1.022, -1.039]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_284.geometry}
        material={materials.mat_177}
        position={[0.543, 1.337, -1.613]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_285.geometry}
        material={materials.mat_178}
        position={[3.818, 1.493, -1.521]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_286.geometry}
        material={materials.mat_178}
        position={[3.818, 1.493, -1.586]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_287.geometry}
        material={materials.mat_178}
        position={[3.818, 1.493, -1.654]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_288.geometry}
        material={materials.mat_178}
        position={[3.34, 0.376, -2.05]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_289.geometry}
        material={materials.mat_178}
        position={[3.397, 0.376, -2.056]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_290.geometry}
        material={materials.mat_178}
        position={[3.456, 0.376, -2.05]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_292.geometry}
        material={materials.mat_179}
        position={[0.517, 1.393, -1.844]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_293.geometry}
        material={materials.mat_179}
        position={[3.8, 1.497, -1.32]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_297.geometry}
        material={materials.mat_181}
        position={[2.189, 0.004, -0.06]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_255.geometry}
        material={materials.mat_184}
        position={[2.94, 0.158, 1.931]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_256.geometry}
        material={materials.mat_184}
        position={[3.675, 1.931, -0.26]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_257.geometry}
        material={materials.mat_185}
        position={[3.716, 0.529, -1.554]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_258.geometry}
        material={materials.mat_186}
        position={[3.871, 0.814, -1.197]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_259.geometry}
        material={materials.mat_186}
        position={[3.877, 0.81, -1.204]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_261.geometry}
        material={materials.mat_92}
        position={[3.134, 0.715, -2.022]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_262.geometry}
        material={materials.mat_188}
        position={[0.496, 0.722, -1.148]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_263.geometry}
        material={materials.mat_189}
        position={[3.471, 1.057, 2.096]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_265.geometry}
        material={materials.mat_191}
        position={[3.941, 1.257, 0.56]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_266.geometry}
        material={materials.mat_191}
        position={[3.952, 1.256, 0.56]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_267.geometry}
        material={materials.mat_192}
        position={[3.773, 1.241, -1.549]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_270.geometry}
        material={materials.mat_195}
        position={[1.213, 0.453, 1.365]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_272.geometry}
        material={materials.mat_195}
        position={[0.769, 0.073, -0.202]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_273.geometry}
        material={materials.mat_195}
        position={[3.688, 1.888, -0.763]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_274.geometry}
        material={materials.mat_195}
        position={[2.442, 0.817, -2.265]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_275.geometry}
        material={materials.mat_196}
        position={[2.995, 0.726, -1.83]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_225.geometry}
        material={materials.mat_198}
        position={[1.044, 0.758, -0.946]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_226.geometry}
        material={materials.mat_198}
        position={[1.044, 0.723, -0.946]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_230.geometry}
        material={materials.mat_200}
        position={[2.169, 1.515, -2.081]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_231.geometry}
        material={materials.mat_200}
        position={[0.464, 1.501, 0.378]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_232.geometry}
        material={materials.mat_156}
        position={[2.096, 2.05, -0.146]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_210.geometry}
        material={materials.mat_205}
        position={[0.545, 1.375, 1.859]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_211.geometry}
        material={materials.mat_205}
        position={[0.542, 1.269, 1.862]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_212.geometry}
        material={materials.mat_206}
        position={[0.452, 1.06, 1.453]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_213.geometry}
        material={materials.mat_207}
        position={[1.22, 1.065, 2.109]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_214.geometry}
        material={materials.mat_91}
        position={[1.203, 1.61, 2.099]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_215.geometry}
        material={materials.mat_91}
        position={[1.198, 1.592, 2.104]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_216.geometry}
        material={materials.mat_91}
        position={[1.227, 1.583, 2.105]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_217.geometry}
        material={materials.mat_91}
        position={[1.245, 1.583, 2.101]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_218.geometry}
        material={materials.mat_208}
        position={[0.762, 1.021, 1.942]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_219.geometry}
        material={materials.mat_70}
        position={[0.382, 1.58, 1.58]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_223.geometry}
        material={materials.mat_211}
        position={[3.965, 1.254, 0.255]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_505.geometry}
        material={materials.mat_105}
        position={[0, 4.079, 3.887]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_509.geometry}
        material={materials['mat_53.001']}
        position={[0, 4.079, 3.887]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_510.geometry}
        material={materials.mat_55}
        position={[0, 4.079, 3.887]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_513.geometry}
        material={materials.mat_105}
        position={[0, 4.079, 3.887]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_515.geometry}
        material={materials['mat_53.001']}
        position={[0, 4.079, 3.887]}
        rotation={[-2.236, 0.359, -0.421]}
        scale={[1, 0.718, 1]}
      />
      
    </group>
  )
}

useGLTF.preload('/models/room.glb')
